/**
 * Sample trace data for the trace viewer demo / empty state.
 *
 * This simulates a PlannerGrounderAgent run on a "Change Font in WordPad" task
 * with 8 steps, including a failure at step 5 (wrong target) and recovery.
 */

import type { Trace } from "./types";

export const SAMPLE_TRACE: Trace = {
  id: "sample_change_font",
  name: "Sample: Change Font (WordPad)",
  metadata: {
    planner_model: "claude-sonnet-4-20250514",
    grounder_model: "gpt-4.1-mini",
    run_name: "demo_trace",
    created_at: "2026-03-22T10:00:00Z",
    source_format: "trajectory_dir",
  },
  episodes: [
    {
      episode_id: "change-font-001",
      task_id: "change-font",
      task_instruction:
        "Open WordPad and change the default font to Arial size 14.",
      score: 1.0,
      success: true,
      num_steps: 8,
      elapsed_seconds: 45.2,
      milestones_passed: 4,
      milestones_total: 4,
      milestones: [
        { description: "WordPad is open", reward: 0.25, passed: true },
        { description: "Font dropdown is open", reward: 0.25, passed: true },
        { description: "Arial is selected", reward: 0.25, passed: true },
        { description: "Size set to 14", reward: 0.25, passed: true },
      ],
      model: "claude-sonnet-4-20250514",
      failure_mode: null,
      steps: [
        {
          step_index: 0,
          action_type: "click",
          target: "Start menu button",
          instruction: "Click the Start menu to search for WordPad",
          reasoning:
            "The task requires opening WordPad. The fastest way is to use the Start menu search. I can see the Start button in the bottom-left corner of the taskbar.",
          decision: "execute",
          coordinate: [24, 752],
          action_history: [],
        },
        {
          step_index: 1,
          action_type: "type",
          target: "Start menu search box",
          instruction: "Type 'wordpad' in the search box",
          reasoning:
            "The Start menu is now open with a search box visible. I need to type 'wordpad' to find the application.",
          decision: "execute",
          typed_text: "wordpad",
          coordinate: [320, 620],
          action_history: ["click(24, 752) on Start menu"],
        },
        {
          step_index: 2,
          action_type: "click",
          target: "WordPad search result",
          instruction: "Click on the WordPad result to open it",
          reasoning:
            "WordPad appears as the top search result. Clicking it will launch the application.",
          decision: "execute",
          coordinate: [320, 280],
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
          ],
        },
        {
          step_index: 3,
          action_type: "click",
          target: "Font family dropdown",
          instruction: "Click the font family dropdown in the toolbar",
          reasoning:
            "WordPad is now open. I can see the font dropdown in the toolbar showing 'Calibri'. I need to click it to open the font selection list.",
          decision: "execute",
          coordinate: [148, 52],
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
            "click(320, 280) on WordPad result",
          ],
        },
        {
          step_index: 4,
          action_type: "click",
          target: "Format menu (WRONG TARGET)",
          instruction: "Select Arial from the font dropdown",
          reasoning:
            "I see a dropdown menu but I'm having trouble locating Arial. Let me try clicking what I think is the font area.",
          decision: "execute",
          coordinate: [450, 320],
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
            "click(320, 280) on WordPad result",
            "click(148, 52) on font dropdown",
          ],
        },
        {
          step_index: 5,
          action_type: "click",
          target: "Font family dropdown (retry)",
          instruction: "The previous click missed. Re-open the font dropdown.",
          reasoning:
            "The previous click was on the wrong area - it clicked the document body instead of the font list. I need to re-click the font dropdown to reopen it.",
          decision: "execute",
          coordinate: [148, 52],
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
            "click(320, 280) on WordPad result",
            "click(148, 52) on font dropdown",
            "click(450, 320) on Format menu (WRONG)",
          ],
        },
        {
          step_index: 6,
          action_type: "click",
          target: "Arial in font list",
          instruction: "Select Arial from the font dropdown list",
          reasoning:
            "The font dropdown is open again. I can now see the list of fonts. Arial should be near the top since fonts are alphabetically ordered. I can see it listed.",
          decision: "execute",
          coordinate: [148, 120],
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
            "click(320, 280) on WordPad result",
            "click(148, 52) on font dropdown",
            "click(450, 320) on Format menu (WRONG)",
            "click(148, 52) on font dropdown (retry)",
          ],
        },
        {
          step_index: 7,
          action_type: "click",
          target: "Font size field",
          instruction: "Click the font size field and change to 14",
          reasoning:
            "Arial is now selected as the font. I need to change the size to 14. The font size field is next to the font name dropdown in the toolbar.",
          decision: "done",
          coordinate: [220, 52],
          typed_text: "14",
          action_history: [
            "click(24, 752) on Start menu",
            "type('wordpad') in search box",
            "click(320, 280) on WordPad result",
            "click(148, 52) on font dropdown",
            "click(450, 320) on Format menu (WRONG)",
            "click(148, 52) on font dropdown (retry)",
            "click(148, 120) on Arial",
          ],
        },
      ],
    },
    {
      episode_id: "copy-file-001",
      task_id: "copy-file",
      task_instruction: "Copy the file 'report.txt' from Desktop to Documents folder.",
      score: 0.5,
      success: false,
      num_steps: 12,
      elapsed_seconds: 62.8,
      milestones_passed: 2,
      milestones_total: 4,
      milestones: [
        { description: "File Explorer is open", reward: 0.25, passed: true },
        { description: "Navigated to Desktop", reward: 0.25, passed: true },
        { description: "File is copied", reward: 0.25, passed: false },
        { description: "File is in Documents", reward: 0.25, passed: false },
      ],
      model: "claude-sonnet-4-20250514",
      failure_mode: "task_incomplete",
      steps: [
        {
          step_index: 0,
          action_type: "click",
          target: "File Explorer in taskbar",
          instruction: "Open File Explorer from the taskbar",
          reasoning: "I need to open File Explorer to navigate to the Desktop folder and find report.txt.",
          decision: "execute",
          coordinate: [72, 752],
          action_history: [],
        },
        {
          step_index: 1,
          action_type: "click",
          target: "Desktop in sidebar",
          instruction: "Click Desktop in the left sidebar",
          reasoning: "File Explorer is open. I can see the navigation sidebar on the left with Desktop listed.",
          decision: "execute",
          coordinate: [80, 200],
          action_history: ["click(72, 752) on File Explorer"],
        },
        {
          step_index: 2,
          action_type: "click",
          target: "report.txt file",
          instruction: "Right-click on report.txt to access copy option",
          reasoning: "I can see report.txt on the Desktop. I need to right-click it to get the context menu with Copy.",
          decision: "execute",
          coordinate: [400, 300],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
          ],
        },
        {
          step_index: 3,
          action_type: "click",
          target: "Copy in context menu",
          instruction: "Click Copy from the context menu",
          reasoning: "The context menu appeared. I can see the Copy option.",
          decision: "execute",
          coordinate: [440, 380],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
            "right_click(400, 300) on report.txt",
          ],
        },
        {
          step_index: 4,
          action_type: "click",
          target: "Documents in sidebar",
          instruction: "Navigate to Documents folder",
          reasoning: "File is copied. Now I need to navigate to the Documents folder to paste it there.",
          decision: "execute",
          coordinate: [80, 240],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
            "right_click(400, 300) on report.txt",
            "click(440, 380) on Copy",
          ],
        },
        {
          step_index: 5,
          action_type: "click",
          target: "Empty area in Documents",
          instruction: "Right-click in empty area to paste",
          reasoning: "I'm in the Documents folder. I need to right-click an empty area to get the Paste option.",
          decision: "execute",
          coordinate: [400, 400],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
            "right_click(400, 300) on report.txt",
            "click(440, 380) on Copy",
            "click(80, 240) on Documents",
          ],
        },
        {
          step_index: 6,
          action_type: "click",
          target: "Paste option (missed)",
          instruction: "Click Paste from the context menu",
          reasoning: "The context menu is showing. Looking for the Paste option.",
          decision: "execute",
          coordinate: [440, 300],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
            "right_click(400, 300) on report.txt",
            "click(440, 380) on Copy",
            "click(80, 240) on Documents",
            "right_click(400, 400) in empty area",
          ],
        },
        {
          step_index: 7,
          action_type: "click",
          target: "Empty area again",
          instruction: "Try right-clicking again in empty area",
          reasoning: "The paste didn't work. The context menu closed. Let me try right-clicking again.",
          decision: "execute",
          coordinate: [400, 450],
          action_history: [
            "click(72, 752) on File Explorer",
            "click(80, 200) on Desktop",
            "right_click(400, 300) on report.txt",
            "click(440, 380) on Copy",
            "click(80, 240) on Documents",
            "right_click(400, 400) in empty area",
            "click(440, 300) on Paste (missed)",
          ],
        },
        {
          step_index: 8,
          action_type: "click",
          target: "Empty area again",
          instruction: "Try right-clicking again",
          reasoning: "Let me try once more to get the paste context menu.",
          decision: "execute",
          coordinate: [400, 450],
          action_history: [
            "...",
            "right_click(400, 400) in empty area",
            "click(440, 300) on Paste (missed)",
            "right_click(400, 450) empty area",
          ],
        },
        {
          step_index: 9,
          action_type: "click",
          target: "Empty area again",
          instruction: "Try right-clicking again",
          reasoning: "Attempting paste again.",
          decision: "execute",
          coordinate: [400, 450],
          action_history: [
            "...",
            "right_click(400, 450) empty area",
            "right_click(400, 450) empty area",
          ],
        },
        {
          step_index: 10,
          action_type: "key",
          target: "Keyboard paste",
          instruction: "Use Ctrl+V to paste the file",
          reasoning: "The right-click context menu approach isn't working reliably. Let me try the keyboard shortcut Ctrl+V instead.",
          decision: "execute",
          key_combo: "Ctrl+V",
          coordinate: [400, 400],
          action_history: [
            "...",
            "right_click(400, 450) empty area (x3)",
          ],
        },
        {
          step_index: 11,
          action_type: "done",
          target: "Task incomplete",
          instruction: "Verify the file was pasted",
          reasoning: "I pressed Ctrl+V but I cannot confirm the file appeared. The task may be incomplete.",
          decision: "fail",
          coordinate: undefined,
          action_history: [
            "...",
            "key(Ctrl+V) to paste",
          ],
        },
      ],
    },
  ],
  summary: {
    total_episodes: 2,
    total_steps: 20,
    success_rate: 0.5,
    avg_score: 0.75,
    avg_steps_per_episode: 10,
    avg_time_per_episode: 54,
    total_time: 108,
    failure_modes: [
      { mode: "task_incomplete", count: 1, percentage: 100 },
    ],
    action_distribution: {
      click: 16,
      type: 1,
      key: 1,
      done: 1,
    },
  },
};
